"""Initial schema

Revision ID: 7426f7f2ba5f
Revises: 
Create Date: 2025-04-11 00:53:34.453871+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7426f7f2ba5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trait_category_association')
    op.drop_constraint(None, 'bonds', type_='foreignkey')
    op.create_foreign_key(None, 'bonds', 'larp_traits', ['id'], ['id'])
    op.add_column('characters', sa.Column('player_name', sa.String(length=100), nullable=False))
    op.add_column('characters', sa.Column('player_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'characters', 'players', ['player_id'], ['id'])
    op.drop_column('characters', 'player')
    op.add_column('chronicles', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('chronicles', sa.Column('storyteller_id', sa.Integer(), nullable=False))
    op.alter_column('chronicles', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'chronicles', 'players', ['storyteller_id'], ['id'])
    op.drop_column('chronicles', 'is_active')
    op.drop_column('chronicles', 'last_modified')
    op.drop_column('chronicles', 'narrator')
    op.drop_constraint(None, 'disciplines', type_='foreignkey')
    op.create_foreign_key(None, 'disciplines', 'larp_traits', ['id'], ['id'])
    op.add_column('larp_traits', sa.Column('display_name', sa.String(length=100), nullable=False))
    op.add_column('larp_traits', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('larp_traits', 'is_custom')
    op.drop_column('larp_traits', 'note')
    op.drop_column('larp_traits', 'is_spent')
    op.drop_column('larp_traits', 'is_negative')
    op.drop_column('larp_traits', 'is_temporary')
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_column('players', 'chronicle_id')
    op.drop_constraint(None, 'rituals', type_='foreignkey')
    op.create_foreign_key(None, 'rituals', 'larp_traits', ['id'], ['id'])
    op.alter_column('staff', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('staff', 'chronicle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('trait_categories', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('trait_categories', sa.Column('trait_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'trait_categories', 'larp_traits', ['trait_id'], ['id'])
    op.create_foreign_key(None, 'trait_categories', 'trait_category', ['category_id'], ['id'])
    op.drop_column('trait_categories', 'id')
    op.drop_column('trait_categories', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trait_categories', sa.Column('name', sa.VARCHAR(length=50), nullable=False))
    op.add_column('trait_categories', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'trait_categories', type_='foreignkey')
    op.drop_constraint(None, 'trait_categories', type_='foreignkey')
    op.drop_column('trait_categories', 'trait_id')
    op.drop_column('trait_categories', 'category_id')
    op.alter_column('staff', 'chronicle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('staff', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'rituals', type_='foreignkey')
    op.create_foreign_key(None, 'rituals', 'traits', ['id'], ['id'])
    op.add_column('players', sa.Column('chronicle_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'players', 'chronicles', ['chronicle_id'], ['id'])
    op.add_column('larp_traits', sa.Column('is_temporary', sa.BOOLEAN(), nullable=False))
    op.add_column('larp_traits', sa.Column('is_negative', sa.BOOLEAN(), nullable=False))
    op.add_column('larp_traits', sa.Column('is_spent', sa.BOOLEAN(), nullable=False))
    op.add_column('larp_traits', sa.Column('note', sa.VARCHAR(), nullable=True))
    op.add_column('larp_traits', sa.Column('is_custom', sa.BOOLEAN(), nullable=False))
    op.drop_column('larp_traits', 'description')
    op.drop_column('larp_traits', 'display_name')
    op.drop_constraint(None, 'disciplines', type_='foreignkey')
    op.create_foreign_key(None, 'disciplines', 'traits', ['id'], ['id'])
    op.add_column('chronicles', sa.Column('narrator', sa.VARCHAR(length=100), nullable=False))
    op.add_column('chronicles', sa.Column('last_modified', sa.DATETIME(), nullable=False))
    op.add_column('chronicles', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    op.drop_constraint(None, 'chronicles', type_='foreignkey')
    op.alter_column('chronicles', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('chronicles', 'storyteller_id')
    op.drop_column('chronicles', 'end_date')
    op.add_column('characters', sa.Column('player', sa.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.drop_column('characters', 'player_id')
    op.drop_column('characters', 'player_name')
    op.drop_constraint(None, 'bonds', type_='foreignkey')
    op.create_foreign_key(None, 'bonds', 'traits', ['id'], ['id'])
    op.create_table('trait_category_association',
    sa.Column('trait_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['trait_categories.id'], ),
    sa.ForeignKeyConstraint(['trait_id'], ['larp_traits.id'], ),
    sa.PrimaryKeyConstraint('trait_id', 'category_id')
    )
    # ### end Alembic commands ### 